### ISSUE TITLE
manage.py or kitedb

### ISSUE THREAD

**Issue by DanielMarchand** [mkite-group/mkite_docs#2]
Often in the docs kitedb and manage.py are used somewhat interchangeably. I'm guessing that it would be better to just swap all manage.py to kitedb, but maybe I'm missing something?

**Comment by dskoda** [comment]
Correct - `kitedb` is a command that invokes `manage.py`. Django users will be familiar with the `manage.py`, but the `kitedb` is just more convenient if the package is installed and the user doesn't know how (or doesn't want) to access the `manage.py` file). I will clarify this issue. Thank you, Daniel

**Comment by dskoda** [comment]
Closed by commit **b43f813daf709821498bccdf2f6407e95a865c71**
